//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clashCenter.Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClashCenterEntities : DbContext
    {
        public ClashCenterEntities()
            : base("name=ClashCenterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Clan> Clans { get; set; }
        public virtual DbSet<ClanHistory> ClanHistories { get; set; }
        public virtual DbSet<ClanHistoryMember> ClanHistoryMembers { get; set; }
    }
}
