//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clashCenter.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favorite
    {
        public int FavoriteID { get; set; }
        public string UserID { get; set; }
        public string FavoriteType { get; set; }
        public string ClashType { get; set; }
        public string ClashTargetID { get; set; }
        public System.DateTime CreaatedDate { get; set; }
        public bool Pinned { get; set; }
        public bool Deleted { get; set; }
    }
}
